// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAPEG1DYK9zlHZIqOgVPwEML9ph5aEFtmA',
    appId: '1:548043523282:web:1532c3030d6e61779e590b',
    messagingSenderId: '548043523282',
    projectId: 'shared-calendar-5958a',
    authDomain: 'shared-calendar-5958a.firebaseapp.com',
    storageBucket: 'shared-calendar-5958a.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD8gv_TPA49cVl5dRdqiINLZfsfKEGRqU8',
    appId: '1:548043523282:android:357bd818b24b15669e590b',
    messagingSenderId: '548043523282',
    projectId: 'shared-calendar-5958a',
    storageBucket: 'shared-calendar-5958a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCgJ_HFLGmQoXC_IlnTpB-PmrETpPXUpKE',
    appId: '1:548043523282:ios:2c9359b4450326809e590b',
    messagingSenderId: '548043523282',
    projectId: 'shared-calendar-5958a',
    storageBucket: 'shared-calendar-5958a.firebasestorage.app',
    iosBundleId: 'com.example.sharedCalendar',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCgJ_HFLGmQoXC_IlnTpB-PmrETpPXUpKE',
    appId: '1:548043523282:ios:2c9359b4450326809e590b',
    messagingSenderId: '548043523282',
    projectId: 'shared-calendar-5958a',
    storageBucket: 'shared-calendar-5958a.firebasestorage.app',
    iosBundleId: 'com.example.sharedCalendar',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAPEG1DYK9zlHZIqOgVPwEML9ph5aEFtmA',
    appId: '1:548043523282:web:6d0b38638190bb119e590b',
    messagingSenderId: '548043523282',
    projectId: 'shared-calendar-5958a',
    authDomain: 'shared-calendar-5958a.firebaseapp.com',
    storageBucket: 'shared-calendar-5958a.firebasestorage.app',
  );
}
